/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LedList {
    }
}
declare global {
    interface HTMLLedListElement extends Components.LedList, HTMLStencilElement {
    }
    var HTMLLedListElement: {
        prototype: HTMLLedListElement;
        new (): HTMLLedListElement;
    };
    interface HTMLElementTagNameMap {
        "led-list": HTMLLedListElement;
    }
}
declare namespace LocalJSX {
    interface LedList {
    }
    interface IntrinsicElements {
        "led-list": LedList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "led-list": LocalJSX.LedList & JSXBase.HTMLAttributes<HTMLLedListElement>;
        }
    }
}
